version: "1.1"
stages:
  - stage:
      - manual-review:
          alias: manual-review
          description: 在流水线过程中添加人工确认步骤
          version: "1.0"
          params:
            processor:
              - "2"
            wating_time: 5
  - stage:
      - git-checkout:
          alias: git-checkout
          description: 代码仓库克隆
          version: "1.0"
          params:
            branch: ((gittar.branch))
            depth: 1
            password: ((gittar.password))
            uri: ((gittar.repo))
            username: ((gittar.username))
